/*global systemDictionary:true */
/*
+===================== DO NOT MODIFY ======================+
| This file was generated by translate-adapter, please use |
| `translate-adapter adminLanguages2words` to update it.   |
+===================== DO NOT MODIFY ======================+
*/
'use strict';

systemDictionary = {
    "Basic settings": {                               "en": "Basic settings",                                   "de": "Grundeinstellungen",                               "ru": "Базовые настройки",                                "pt": "Configurações básicas",                            "nl": "Basis instellingen",                               "fr": "Paramètres de base",                               "it": "Impostazioni di base",                             "es": "Ajustes básicos",                                  "pl": "Podstawowe ustawienia",                            "uk": "Основні налаштування",                             "zh-cn": "基本设置"},
    "Wallbox": {                                      "en": "Wallbox",                                          "de": "Wallbox",                                          "ru": "Настенная коробка",                                "pt": "Wallbox",                                          "nl": "Wallbox",                                          "fr": "Boîte murale",                                     "it": "Scatola da muro",                                  "es": "Caja de pared",                                    "pl": "Skrzynka ścienna",                                 "uk": "Wallbox",                                          "zh-cn": "壁箱"},
    "Device url": {                                   "en": "Device url",                                       "de": "Geräte-URL",                                       "ru": "URL-адрес устройства",                             "pt": "URL do dispositivo",                               "nl": "Apparaat-URL",                                     "fr": "URL de l'appareil",                                "it": "URL del dispositivo",                              "es": "URL del dispositivo",                              "pl": "Adres URL urządzenia",                             "uk": "URL-адреса пристрою",                              "zh-cn": "设备网址"},
};